version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

# ye btayega ki hum ek hi entwork pe dono airflow and postfgres ko common netwrok pe run krne hai 
# is wajah  se ye dono services ek dusre ko access kr payenge aur communicate kr payenge
networks:
  airflow_network:
    external: false

volumes:
  postgres_data: